---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)

data <- read.csv(unzip("activity.zip"), header=T)
```

## What is mean total number of steps taken per day?
```{r mean_total_steps, echo=TRUE}
df <- group_by(data, date) %>% summarize(totalsteps = sum(steps, na.rm=TRUE))
p <- ggplot(df, aes(x=totalsteps)) + geom_histogram(binwidth=200) +
        scale_y_continuous(breaks=seq(0,10),limits=c(0,10))　+
        xlab("total number of steps") +
        labs(title="Total Number of Steps Taken Each Day")
print(p)
ggsave("./figure/plot1.png", p)

df %>% summarize(mean = mean(totalsteps), median = median(totalsteps))
```

## What is the average daily activity pattern?
```{r average_daily_pattern, echo=TRUE}
df <- group_by(data, interval) %>% summarize(avsteps = mean(steps, na.rm=TRUE))
p <- ggplot(df, aes(x=interval, y=avsteps)) + geom_line() +
        scale_x_continuous(breaks=seq(0,2400,200),limits=c(0,2400))　+
        xlab("5-minute interval") +  ylab("the average number of steps") +
        labs(title="The Average Number of Steps Taken")
print(p)
ggsave("./figure/plot2.png", p)

df %>% summarize(average = mean(avsteps), maximum = max(avsteps))
```


## Imputing missing values
```{r missing, echo=TRUE}
### the total number of the missing values in the dataset 
sum(is.na(data$steps))

nadata <- data[is.na(data$steps),]
nadata$steps <- df[match(c(nadata$interval), c(df$interval)),]$avsteps
newdata <- rbind(nadata, data[!is.na(data$steps),])

ndf <- group_by(newdata, date) %>% summarize(totalsteps = sum(steps, na.rm=TRUE))
p <- ggplot(ndf, aes(x=totalsteps)) + geom_histogram(binwidth=200) +
        scale_y_continuous(breaks=seq(0,10),limits=c(0,10))　+
        xlab("total number of steps") +
        labs(title="Total Number of Steps Taken Each Day After Missing Values Are Imputed")
print(p)
ggsave("./figure/plot3.png", p)

### representing the mean and median total number of steps taken per day.
ndf %>% summarize(mean = mean(totalsteps), median = median(totalsteps))
```

## Are there differences in activity patterns between weekdays and weekends?
```{r panelplot, echo=TRUE}
days <- weekdays(as.Date(newdata$date))
days[days %in% c("月曜日", "火曜日", "水曜日", "木曜日", "金曜日")]<-"weekday"
days[days %in% c("土曜日", "日曜日")]<-"weekend"
days <- factor(days)
newdata <- cbind(newdata, days)

ndf <- group_by(newdata, interval, days) %>% summarize(avsteps = mean(steps, na.rm=TRUE))
p <- ggplot(ndf, aes(x=interval, y=avsteps, color=days)) + 
        geom_line(na.rm=TRUE) +
        scale_x_continuous(breaks=seq(0,2400,200),limits=c(0,2400))　+
        xlab("5-minute interval") + ylab("the average number of steps") +
        labs(title="The average number of steps taken per 5-minute interval")
print(p)
ggsave("./figure/plot4.png",p)
```